org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Which Minecraft version to build. Override per build with -Pmc=26.2
mc=26.3

# Minecraft 26.3
mc_26_3_fabric_api=0.161.0+26.3
mc_26_3_neoforge=26.3.0.43-beta
mc_26_3_modmenu=21.0.0-beta.1
mc_26_3_cloth_config=26.3.158

# Minecraft 26.2
mc_26_2_fabric_api=0.161.0+26.2
mc_26_2_neoforge=26.2.0.88
mc_26_2_modmenu=20.0.1
mc_26_2_cloth_config=26.2.155

# Toolchain
loader_version=0.19.5
loom_version=1.17.20
moddev_version=2.0.147

# Mod properties
mod_id=hitindication
mod_version=2.0.0
maven_group=com.rosymaple.hitindication
archives_base_name=hitindication
